<a href="https://colab.research.google.com/github/lokesh2004-g/NLP-Project/blob/main/simple_rnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('/content/100_Unique_QA_Dataset.csv')
df.head()

                                          question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

In [42]:
#tokenize
def tokenize(text):
  text=text.lower()
  text=text.replace('?','')
  text=text.replace("'","")
  return text.split()

In [43]:
tokenize("What is the capital of France?")

['what', 'is', 'the', 'capital', 'of', 'france']

In [44]:
#vocablary
vocab={'<UNK>':0}

In [45]:
def build_vocab(row):
  tokenize_questions=tokenize(row['question'])
  tokenize_answer=tokenize(row['answer'])
  merge_tokens=tokenize_answer+tokenize_questions
  for token in merge_tokens:
    if token not in vocab:
      vocab[token]=len(vocab)

In [46]:
df.apply(build_vocab,axis=1)

0     None
1     None
2     None
3     None
4     None
      ...
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [47]:
vocab

{'<UNK>': 0,
 'paris': 1,
 'what': 2,
 'is': 3,
 'the': 4,
 'capital': 5,
 'of': 6,
 'france': 7,
 'berlin': 8,
 'germany': 9,
 'harper-lee': 10,
 'who': 11,
 'wrote': 12,
 'to': 13,
 'kill': 14,
 'a': 15,
 'mockingbird': 16,
 'jupiter': 17,
 'largest': 18,
 'planet': 19,
 'in': 20,
 'our': 21,
 'solar': 22,
 'system': 23,
 '100': 24,
 'boiling': 25,
 'point': 26,
 'water': 27,
 'celsius': 28,
 'leonardo-da-vinci': 29,
 'painted': 30,
 'mona': 31,
 'lisa': 32,
 '8': 33,
 'square': 34,
 'root': 35,
 '64': 36,
 'au': 37,
 'chemical': 38,
 'symbol': 39,
 'for': 40,
 'gold': 41,
 '1945': 42,
 'which': 43,
 'year': 44,
 'did': 45,
 'world': 46,
 'war': 47,
 'ii': 48,
 'end': 49,
 'nile': 50,
 'longest': 51,
 'river': 52,
 'tokyo': 53,
 'japan': 54,
 'albert-einstein': 55,
 'developed': 56,
 'theory': 57,
 'relativity': 58,
 '32': 59,
 'freezing': 60,
 'fahrenheit': 61,
 'mars': 62,
 'known': 63,
 'as': 64,
 'red': 65,
 'george-orwell': 66,
 'author': 67,
 '1984': 68,
 'pound': 69,
 'currency': 70,
 'united': 71,
 'kingdom': 72,
 'delhi': 73,
 'india': 74,
 'newton': 75,
 'discovered': 76,
 'gravity': 77,
 '7': 78,
 'how': 79,
 'many': 80,
 'continents': 81,
 'are': 82,
 'there': 83,
 'on': 84,
 'earth': 85,
 'co2': 86,
 'gas': 87,
 'do': 88,
 'plants': 89,
 'use': 90,
 'photosynthesis': 91,
 '2': 92,
 'smallest': 93,
 'prime': 94,
 'number': 95,
 'alexander-graham-bell': 96,
 'invented': 97,
 'telephone': 98,
 'canberra': 99,
 'australia': 100,
 'pacific-ocean': 101,
 'ocean': 102,
 '299,792,458m/s': 103,
 'speed': 104,
 'light': 105,
 'vacuum': 106,
 'portuguese': 107,
 'language': 108,
 'spoken': 109,
 'brazil': 110,
 'alexander-fleming': 111,
 'penicillin': 112,
 'ottawa': 113,
 'canada': 114,
 'whale': 115,
 'mammal': 116,
 'hydrogen': 117,
 'element': 118,
 'has': 119,
 'atomic': 120,
 '1': 121,
 'everest': 122,
 'tallest': 123,
 'mountain': 124,
 'newyork': 125,
 'city': 126,
 'big': 127,
 'apple': 128,
 'planets': 129,
 'vangogh': 130,
 'starry': 131,
 'night': 132,
 'h2o': 133,
 'formula': 134,
 'rome': 135,
 'italy': 136,
 'country': 137,
 'famous': 138,
 'sushi': 139,
 'armstrong': 140,
 'was': 141,
 'first': 142,
 'person': 143,
 'step': 144,
 'moon': 145,
 'avocado': 146,
 'main': 147,
 'ingredient': 148,
 'guacamole': 149,
 '6': 150,
 'sides': 151,
 'does': 152,
 'hexagon': 153,
 'have': 154,
 'yuan': 155,
 'china': 156,
 'jane-austen': 157,
 'pride': 158,
 'and': 159,
 'prejudice': 160,
 'fe': 161,
 'iron': 162,
 'diamond': 163,
 'hardest': 164,
 'natural': 165,
 'substance': 166,
 'asia': 167,
 'continent': 168,
 'by': 169,
 'area': 170,
 'george-washington': 171,
 'president': 172,
 'states': 173,
 'parrot': 174,
 'bird': 175,
 'its': 176,
 'ability': 177,
 'mimic': 178,
 'sounds': 179,
 'simpsons': 180,
 'longest-running': 181,
 'animated': 182,
 'tv': 183,
 'show': 184,
 'vaticancity': 185,
 'saturn': 186,
 'most': 187,
 'moons': 188,
 'shakespeare': 189,
 'romeo': 190,
 'juliet': 191,
 'nitrogen': 192,
 'earths': 193,
 'atmosphere': 194,
 '206': 195,
 'bones': 196,
 'adult': 197,
 'human': 198,
 'body': 199,
 'mercury': 200,
 'metal': 201,
 'liquid': 202,
 'at': 203,
 'room': 204,
 'temperature': 205,
 'moscow': 206,
 'russia': 207,
 'benjamin-franklin': 208,
 'electricity': 209,
 'second-largest': 210,
 'land': 211,
 'yellow': 212,
 'color': 213,
 'ripe': 214,
 'banana': 215,
 'february': 216,
 'month': 217,
 '28': 218,
 'days': 219,
 'common': 220,
 'biology': 221,
 'study': 222,
 'living': 223,
 'organisms': 224,
 'called': 225,
 'home': 226,
 'great': 227,
 'wall': 228,
 'nectar': 229,
 'bees': 230,
 'collect': 231,
 'from': 232,
 'flowers': 233,
 'opposite': 234,
 'day': 235,
 'seoul': 236,
 'south': 237,
 'korea': 238,
 'edison': 239,
 'bulb': 240,
 'oxygen': 241,
 'humans': 242,
 'breathe': 243,
 'survival': 244,
 '12': 245,
 '144': 246,
 'egypt': 247,
 'pyramids': 248,
 'giza': 249,
 'octopus': 250,
 'sea': 251,
 'creature': 252,
 'eight': 253,
 'arms': 254,
 'christmas': 255,
 'holiday': 256,
 'celebrated': 257,
 'december': 258,
 '25': 259,
 'yen': 260,
 'legs': 261,
 'spider': 262,
 'basketball': 263,
 'sport': 264,
 'uses': 265,
 'net,': 266,
 'ball,': 267,
 'hoop': 268,
 'kangaroos': 269,
 'margaretthatcher': 270,
 'female': 271,
 'minister': 272,
 'uk': 273,
 'cheetah': 274,
 'fastest': 275,
 'animal': 276,
 'periodic': 277,
 'table': 278,
 'madrid': 279,
 'spain': 280,
 'closest': 281,
 'sun': 282,
 'charlesbabbage': 283,
 'father': 284,
 'computers': 285,
 'mexicocity': 286,
 'mexico': 287,
 'colors': 288,
 'rainbow': 289,
 'piano': 290,
 'musical': 291,
 'instrument': 292,
 'black': 293,
 'white': 294,
 'keys': 295,
 'christophercolumbus': 296,
 'americas': 297,
 '1492': 298,
 'pinocchio': 299,
 'disney': 300,
 'character': 301,
 'long': 302,
 'nose': 303,
 'grows': 304,
 'it': 305,
 'when': 306,
 'lying': 307,
 'jamescameron': 308,
 'directed': 309,
 'movie': 310,
 'titanic': 311,
 'batman': 312,
 'superhero': 313,
 'also': 314,
 'dark': 315,
 'knight': 316,
 'brasilia': 317,
 'mango': 318,
 'fruit': 319,
 'king': 320,
 'fruits': 321,
 'eiffel': 322,
 'tower': 323}

In [48]:
len(vocab)

324

In [49]:
def text_to_indices(text,vocab):
  index_text=[]
  for token in tokenize(text):
    if token in vocab:
      index_text.append(vocab[token])
    else:
      index_text.append(vocab['<UNK>'])


  return index_text

In [50]:
text_to_indices("What is my name",vocab)

[2, 3, 0, 0]

In [55]:
import torch
from torch.utils.data import  Dataset ,DataLoader

In [65]:
class QansDataset(Dataset):
  def __init__(self,df,vocab):
    self.df=df
    self.vocab=vocab

  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self,index):
    numerical_question=text_to_indices(self.df.iloc[index]['question'],self.vocab)
    numerical_answer=text_to_indices(self.df.iloc[index]['answer'],self.vocab)
    return torch.tensor(numerical_question),torch.tensor(numerical_answer)

In [66]:
dataset=QansDataset(df,vocab)

In [70]:
dataset[0]

(tensor([2, 3, 4, 5, 6, 7]), tensor([1]))

In [72]:
dataloader=DataLoader(dataset,batch_size=1,shuffle=True)

In [73]:
for question,answer in dataloader:
  print(question,answer)

tensor([[ 11, 141,   4, 142, 143,  13, 144,  84,   4, 145]]) tensor([[140]])
tensor([[ 11,  12, 190, 159, 191]]) tensor([[189]])
tensor([[ 11,   3,  63,  64,   4, 284,   6, 285]]) tensor([[283]])
tensor([[  2,   3,   4,  18, 116,  84,  85]]) tensor([[115]])
tensor([[ 43, 291, 292, 119, 293, 159, 294, 295]]) tensor([[290]])
tensor([[ 43, 217, 119, 218, 219,  20,  15, 220,  44]]) tensor([[216]])
tensor([[  2,   3,   4,   5,   6, 114]]) tensor([[113]])
tensor([[2, 3, 4, 5, 6, 7]]) tensor([[1]])
tensor([[ 43, 118, 119,   4, 120,  95, 121]]) tensor([[117]])
tensor([[ 11,  76, 112]]) tensor([[111]])
tensor([[ 43, 102,   3,   4,  18]]) tensor([[101]])
tensor([[  2,   3,   4, 147,  87,  20, 193, 194]]) tensor([[192]])
tensor([[ 43,  87,  88, 242, 243,  20,  40, 244]]) tensor([[241]])
tensor([[  2,   3,   4,  93, 137,  20,   4,  46]]) tensor([[185]])
tensor([[ 43, 168,   3,   4,  18, 169, 170]]) tensor([[167]])
tensor([[ 11,  76, 209]]) tensor([[208]])
tensor([[11, 76, 77]]) tensor([[75]])
tensor([[  2,  88, 230, 231, 232, 233]]) tensor([[229]])
tensor([[  2,   3,   4, 213,   6,  15, 214, 215]]) tensor([[212]])
tensor([[ 43,  19, 119,   4, 187, 188]]) tensor([[186]])
tensor([[43, 87, 88, 89, 90, 40, 91]]) tensor([[86]])
tensor([[ 43, 313,   3, 314,  63,  64,   4, 315, 316]]) tensor([[312]])
tensor([[  2,   3,   4,   5,   6, 237, 238]]) tensor([[236]])
tensor([[  2,   3,   4, 181, 182, 183, 184]]) tensor([[180]])
tensor([[ 11, 309,   4, 310, 311]]) tensor([[308]])
tensor([[11, 97,  4, 98]]) tensor([[96]])
tensor([[ 43, 137,   3, 138,  40, 139]]) tensor([[54]])
tensor([[ 2,  3,  4, 34, 35,  6, 36]]) tensor([[33]])
tensor([[ 43, 137,   3, 226,  13,   4, 227, 228]]) tensor([[156]])
tensor([[ 43, 175,   3,  63,  40, 176, 177,  13, 178, 179]]) tensor([[174]])
tensor([[  2,   3,   4,   5,   6, 287]]) tensor([[286]])
tensor([[  2,   3,   4,   5,   6, 207]]) tensor([[206]])
tensor([[  2,   3,   4, 234,   6, 235]]) tensor([[132]])
tensor([[ 43, 251, 252, 119, 253, 254]]) tensor([[250]])
tensor([[ 43,   3,   4, 210, 137, 169, 211, 170]]) tensor([[114]])
tensor([[  2,   3,   4, 164, 165, 166,  84,  85]]) tensor([[163]])
tensor([[ 2,  3,  4, 38, 39, 40, 41]]) tensor([[37]])
tensor([[ 11,  12, 158, 159, 160]]) tensor([[157]])
tensor([[ 79,  80, 196,  82,  20,   4, 197, 198, 199]]) tensor([[195]])
tensor([[ 43, 126,   3,  63,  64,   4, 127, 128]]) tensor([[125]])
tensor([[ 43, 137, 119,   4, 248,   6, 249]]) tensor([[247]])
tensor([[  2,   3,   4, 147, 148,  20, 149]]) tensor([[146]])
tensor([[ 43, 300, 301, 119,  15, 302, 303, 159, 304, 305, 306, 307]]) tensor([[299]])
tensor([[43, 19,  3, 63, 64,  4, 65, 19]]) tensor([[62]])
tensor([[79, 80, 81, 82, 83, 84, 85]]) tensor([[78]])
tensor([[  2,   3,   4,  34,  35,   6, 246]]) tensor([[245]])
tensor([[ 2,  3,  4,  5,  6, 74]]) tensor([[73]])
tensor([[  2,   3,   4,   5,   6, 100]]) tensor([[99]])
tensor([[ 2,  3,  4, 70,  6, 54]]) tensor([[260]])
tensor([[ 43, 201,   3,  15, 202, 203, 204, 205]]) tensor([[200]])
tensor([[ 43, 319,   3,  63,  64,   4, 320,   6, 321]]) tensor([[318]])
tensor([[ 79,  80, 288,  82,  20,  15, 289]]) tensor([[78]])
tensor([[ 79,  80, 151, 152,  15, 153, 154]]) tensor([[150]])
tensor([[  2,   3,   4,   5,   6, 136]]) tensor([[135]])
tensor([[ 43, 108,   3, 109,  20, 110]]) tensor([[107]])
tensor([[11,  3,  4, 67,  6, 68]]) tensor([[66]])
tensor([[ 2,  3,  4, 60, 26,  6, 27, 20, 61]]) tensor([[59]])
tensor([[  2,   3,   4,   5,   6, 110]]) tensor([[317]])
tensor([[43, 44, 45, 46, 47, 48, 49]]) tensor([[42]])
tensor([[ 2,  3,  4, 25, 26,  6, 27, 20, 28]]) tensor([[24]])
tensor([[ 11,  97,   4, 105, 240]]) tensor([[239]])
tensor([[11, 30,  4, 31, 32]]) tensor([[29]])
tensor([[  2,   3,   4, 222,   6, 223, 224, 225]]) tensor([[221]])
tensor([[ 2,  3,  4, 51, 52, 20,  4, 46]]) tensor([[50]])
tensor([[ 11, 141,   4, 142, 172,   6,   4,  71, 173]]) tensor([[171]])
tensor([[11, 12, 13, 14, 15, 16]]) tensor([[10]])
tensor([[ 79,  80, 129,  82,  20,   4,  22,  23]]) tensor([[33]])
tensor([[ 2,  3,  4,  5,  6, 54]]) tensor([[53]])
tensor([[ 43,   3,   4, 275, 211, 276]]) tensor([[274]])
tensor([[ 43, 256,   3, 257,  84, 258, 259]]) tensor([[255]])
tensor([[ 79,  80, 261, 152,  15, 262, 154]]) tensor([[33]])
tensor([[ 2,  3,  4, 93, 94, 95]]) tensor([[92]])
tensor([[11, 56,  4, 57,  6, 58]]) tensor([[55]])
tensor([[ 43,  19,   3,   4, 281,  13,   4, 282]]) tensor([[200]])
tensor([[  2,   3,   4, 104,   6, 105,  20, 106]]) tensor([[103]])
tensor([[2, 3, 4, 5, 6, 9]]) tensor([[8]])
tensor([[  2,   3,   4, 123, 124,  20,   4,  46]]) tensor([[122]])
tensor([[  2,   3,   4,  70,   6, 156]]) tensor([[155]])
tensor([[ 2,  3,  4, 18, 19, 20, 21, 22, 23]]) tensor([[17]])
tensor([[  2,   3,   4,   5,   6, 280]]) tensor([[279]])
tensor([[ 11, 141,   4, 142, 271,  94, 272,   6,   4, 273]]) tensor([[270]])
tensor([[  2,   3,   4,  38,  39,  40, 162]]) tensor([[161]])
tensor([[  2,   3,   4, 142, 118,  84,   4, 277, 278]]) tensor([[117]])
tensor([[ 43, 264, 265,  15, 266, 267, 159, 268]]) tensor([[263]])
tensor([[ 43, 137,   3, 138,  40, 176, 269]]) tensor([[100]])
tensor([[ 11,  76,   4, 297,  20, 298]]) tensor([[296]])
tensor([[ 2,  3,  4, 70,  6,  4, 71, 72]]) tensor([[69]])
tensor([[  2,   3,   4,  38, 134,   6,  27]]) tensor([[133]])
tensor([[ 43, 137,   3,  63,  40,   4, 322, 323]]) tensor([[7]])
tensor([[ 11,  30, 131, 132]]) tensor([[130]])

In [74]:
import torch.nn as nn

In [89]:
class SimpleRnn(nn.Module):
  def __init__(self,vocab_size):
    super().__init__()
    self.embedding=nn.Embedding(vocab_size,embedding_dim=50)
    self.rnn=nn.RNN(50,64,batch_first=True)
    self.outlayer=nn.Linear(64,vocab_size)
  def forward(self,question):
    emeb_question=self.embedding(question)
    hidden,final=self.rnn(emeb_question)
    output=self.outlayer(final.squeeze(0))
    return output

In [90]:
learning_rate=0.001
epochs=20

In [91]:
model=SimpleRnn(len(vocab))

In [92]:
criterion=nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(model.parameters(),lr=learning_rate)

In [93]:
for epoch in range(epochs):
  total_loss=0
  for question, answer in dataloader:
    optimizer.zero_grad()
    output=model(question)
    loss=criterion(output,answer[0])
    loss.backward()
    optimizer.step()
    total_loss=total_loss+loss.item()
  print(f'loss:{total_loss} epoch {epoch}')

loss:526.3536348342896 epoch 0
loss:453.89380502700806 epoch 1
loss:373.14957189559937 epoch 2
loss:314.0821268558502 epoch 3
loss:263.3827438354492 epoch 4
loss:215.24214923381805 epoch 5
loss:172.33228731155396 epoch 6
loss:134.91136574745178 epoch 7
loss:104.63899332284927 epoch 8
loss:79.89688494801521 epoch 9
loss:61.99301120638847 epoch 10
loss:48.57312847673893 epoch 11
loss:38.80313827097416 epoch 12
loss:31.41982391476631 epoch 13
loss:25.7486906722188 epoch 14
loss:21.61268512904644 epoch 15
loss:18.13682059943676 epoch 16
loss:15.276350155472755 epoch 17
loss:13.187417447566986 epoch 18
loss:11.38812755420804 epoch 19

In [101]:
def predict(model,question,threshold=.3):
  numerical_question=text_to_indices(question,vocab)
  question_tensor=torch.tensor(numerical_question).unsqueeze(0)
  model.eval()
  output=model(question_tensor)
  probs=torch.nn.functional.softmax(output,dim=1)
  value, index = torch.max(probs, dim=1)

  if value < threshold:
    print("I don't know")

  print(list(vocab.keys())[index])

In [102]:
predict(model, "What is the largest planet in our solar system?")

jupiter